---

- name: playbook 
  hosts: all
  become: true
  vars:
    message1: Privet
    message2: World
    secret: dfskdjfls
    owner: name
  tasks:
    - name: Print secret var
      debug:
        var: secret
    - name: debuggin 
      debug:
        msg: "Secret word is: {{ secret }}"
    - name: settings facts
      set_fact: 
        full_message: "{{ message1 }} {{ message2 }} from {{ owner }}"
    - name: yo
      debug:
        var: full_message
