---

- name: playbook 
  hosts: all
  become: true
  tasks:
    - name: Copy docker-compose files
      copy:
        src: ./files/docker-compose.yml
        dest: /home/maga/time-app-project/docker-compose.yml
        owner: maga
        group: maga
    - name: Run docker-compose
      shell: docker-compose -f /home/maga/time-app-project/docker-compose.yml up -d  
      register: output
    - name: show results
      ansible.builtin.debug:
        var: output
